apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: {{CI_REGISTRY_IMAGE}}/chatbot:latest
        env:
        - name: LLM_ENDPOINT
          value: "https://chat-large.llm.mylab.th-luebeck.dev/v1"
        ports:
        - containerPort: 8501
        resources:
          limits:
            memory: 1000M
            cpu: 250m
          requests:
            memory: 250M
            cpu: 100m
        volumeMounts:
        - name: data
          mountPath: /data
      imagePullSecrets:
      - name: gitlab-registry-{{CI_PROJECT_ID}}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: demo-data
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
  labels:
    app: chatbot
spec:
  type: ClusterIP
  selector:
    app: chatbot
  ports:
  - name: http
    port: 80
    targetPort: 8501