apiVersion: batch/v1
kind: Job
metadata:
  name: indexing
spec:
  template:
    spec:
      containers:
      - name: indexer
        image: {{CI_REGISTRY_IMAGE}}/indexer:latest
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: demo-data
      imagePullSecrets:
      - name: gitlab-registry-{{CI_PROJECT_ID}}