apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    acme.cert-manager.io/http01-edit-in-place: 'true'
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: chatbot-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbot
            port:
              number: 8501
  - host: chatbot-rag-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chatbot-rag
            port:
              number: 8501
  - host: frontend-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
  - host: langserve-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: langserve
              port:
                number: 8080
  tls:
    - hosts:
        - chatbot-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
        - chatbot-rag-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
        - frontend-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
        - langserve-{{CI_PROJECT_ID}}.llm.mylab.th-luebeck.dev
      secretName: chatbot-{{CI_PROJECT_ID}}-ingress-cert